#f = open("one.txt","r")
#data = f.read()
#print("File content:",data)
#f.close()
#f = open("one.txt","r")
#data = f.read(25)
#print("Content:",data)
#f.close()
#f = open("one.txt","r")
#line1 = f.readline()
#print("line 1 :",line1)
#f.close()
#f = open("one.txt","r")
#lines = f.readlines()
#print("List of lines:",lines)
#print("Number of line:",len(lines))
#f.close()
f = open("one.txt","r")
lines = f.readlines()
print(lines[1].strip())
f.close()



